### ISSUE TITLE
ERC1155 Sell and Bid orders error 400

### ISSUE THREAD

**Issue by TheAlexandru** [rarible/protocol-ethereum-sdk#52]
When placing a bid or sell order on an ERC1155 token from the SDK, I get this error every time.
I'm testing on Rinkeby network.

The error:
`Failed to load resource: the server responded with a status of 400 ()`

Here is the full request that I do:

`
curl 'https: //ethereum-api-staging.rarible.org/v0.1/order/orders' \
  -H 'authority: ethereum-api-staging.rarible.org' \
  -H 'user-agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/94.0.4606.61 Safari/537.36' \
  -H 'content-type: application/json' \
  -H 'accept: */*' \
  -H 'sec-gpc: 1' \
  -H 'origin: https://rarible-demo.bubbleapps.io' \
  -H 'sec-fetch-site: cross-site' \
  -H 'sec-fetch-mode: cors' \
  -H 'sec-fetch-dest: empty' \
  -H 'referer: https://rarible-demo.bubbleapps.io/' \
  -H 'accept-language: en-GB,en-US;q=0.9,en;q=0.8' \
  --data-raw '{"maker":"0xbea9938565b830a263162c86de7642177fa08004","make":{"assetType":{"@type":"ERC1155","contract":"0x1af7a7555263f275433c6bb0b8fdcd231f89b1d7","tokenId":"86239056537866358507050266989756184312317378498709552951663058336055197433857","uri":"QmVeSu3CNqY6PVTkDFzABvQwtBLrK6uwgFZtWo2vMTfmNH","creators":[{"account":"0xbea9938565b830a263162c86de7642177fa08004","value":10000}],"royalties":[{"account":"0xbea9938565b830a263162c86de7642177fa08004","value":1000}],"signatures":["0xd3cf1d4d8129d559a65da90e078a555906e43989226a3043e660686165043280173751fb645946c1510180b5e512c8a4681262a701297753e8f1ecd054d790db1b"],"supply":"6","assetClass":"ERC721_LAZY"},"value":"1"},"take":{"assetType":{"assetClass":"ETH"},"value":"1000000000000000000"},"type":"RARIBLE_V2","data":{"dataType":"RARIBLE_V2_DATA_V1","payouts":[],"originFees":[]},"salt":"18599704616995546978572909908843229650706680586262049193108086493917652791984","signature":"0xfa5ebd00702c401b4bf7e1c603cecef4e93dcddbb2539bfc76e4e896ad195dd40d98c3bd9a896316ea538699e58b7f9f931aaea5ae5e953193182aabb4dc06f81b"}' \
  --compressed
`

**Comment by eduardstal** [comment]
@evgenynacu said he needs to check this at another time. Feel free to send him a DM on tg

**Comment by TheAlexandru** [comment]
Is this a joke? I was discussing it with him in PM and he said to write it in the issues...

I will wait for SDK bundle update and see if the error will persist.

**Comment by ex1st0r** [comment]
@TheAlexandru please, get the latest version of SDK and try again.

**Comment by TheAlexandru** [comment]
Fixed in the latest version, thank you!
